import { color } from '@rneui/base';
import {StyleSheet} from 'react-native'
import { setText, setWidth,setHeight } from "../../../utils/styleAdb";

export default StyleSheet.create({
    //外层盒子
    wraper:{
        position:'relative',
        marginTop:setWidth(10),
        width:setWidth(980),
        height:setHeight(465),
        backgroundColor:'#fff',
        borderRadius:setWidth(40),
        padding:setWidth(50)
    },
    //每一条内容的外层div
    contentBox:{
         flexDirection:'row',
         marginBottom:setWidth(45)
    },
    //标题
    contentTitle:{
     color:'black'
    },
    //input框
    contentInput:{
        width:setWidth(675),
        paddingVertical:0,
        paddingHorizontal:setWidth(20),
        height:setHeight(55),
        borderRadius:setWidth(45),
        marginLeft:setWidth(45),
        backgroundColor:'white',
        elevation:3,
        shadowColor:'#315CF7',
        shadowOffset:{width:0,height:0},
        shadowOpacity: 1,
        shadowRadius: 2.5,
        textAlign:'center',
        fontSize:setWidth(30)
    },
    //数据选择下拉
    buttonStyle:{
        width:setWidth(675),
        height:setHeight(55),
        borderRadius:setWidth(45),
        backgroundColor:'white',
        elevation:setWidth(3),
        shadowColor:'#315CF7',
        shadowOffset:{width:0,height:0},
        shadowOpacity:setWidth(1),
        shadowRadius: setWidth(2.5),
        marginRight:setWidth(44),
    },
    //按钮中字体展示
    buttonTextStyle:{
        fontSize:setWidth(30)
    },
    //生产日期input
    productionDate:{
        width:setWidth(272),
        height:setHeight(55),
        paddingVertical:0,
        paddingHorizontal:setWidth(20),
        height:setHeight(60),
        borderRadius:setWidth(45),
        marginLeft:setWidth(45),
        backgroundColor:'white',
        elevation:setWidth(3),
        shadowColor:'#315CF7',
        shadowOffset:{width:0,height:0},
        shadowOpacity:setWidth(1),
        shadowRadius:setWidth(2.5),
        textAlign:'left',
        fontSize:setWidth(24),
        lineHeight:setHeight(55),
        color:'black'
    },
    productionBox:{
     justifyContent:'space-between'
    },
    //中间的横线
    line:{
        width:setWidth(53),
        height:0,
        borderColor:'#BDBDC1',
        borderWidth:1,
        marginTop:setWidth(22),
        marginLeft:setWidth(20)
    },
    //start的icon
     startIcon:{
        position:'absolute',
        color:'#4C71FB',
        bottom:setWidth(10),
        right:setWidth(10)
     },
     //endicon
     EndIcon:{
        position:'absolute',
        color:'#4C71FB',
        bottom:setWidth(10),
        right:setWidth(10)
     },
     //底部按钮
     BottomButton:{
      position:'absolute',
      right:setWidth(50),
      bottom:0,
        flexDirection:'row'
      }
      ,
      //按钮盒子
      BtmBox:{
       position:'absolute',
       bottom:setWidth(30),
       right:setWidth(0),
       width:setWidth(90),
       height:setWidth(47),
       borderColor:'#456BF8',
       borderWidth:setWidth(1),
       borderRadius:setWidth(50)
      },
       //盒子内容
      BtmBoxText:{
         fontSize:setText(33),
         textAlign:'center',
         lineHeight:setWidth(40),
         color:'#456BF8'
      },
      //同意按钮margin
      agree:{
        marginRight:setWidth(140)
      }
})